version: '3.4'

services:
  ecopark.presentation:
    image: ${DOCKER_REGISTRY-}ecoparkpresentation
    networks:
      - internal-network
    build:
      context: .
      dockerfile: EcoPark.Presentation/Dockerfile

    ports:
      - "5000:5000"

    environment:
        ASPNETCORE_URLS: "https://+:5000"

  database:
    user: root    
    container_name: Database
    networks:
      - internal-network
    restart: always
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: "Ecopark123!@"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - ../volumes/mssql_data:/var/opt/mssql/data

  storage:
    container_name: 'Storage'
    image: mcr.microsoft.com/azure-storage/azurite:latest  # Update to the latest version
    restart: always
    hostname: azurite
    command: "azurite --blobHost 0.0.0.0 --blobPort 10000 --queueHost 0.0.0.0 --queuePort 10001 --skipApiVersionCheck"
    ports:
        - "10000:10000"
        - "10001:10001"
    volumes:
        - ../volumes/azure_data:/data
    networks:
        - internal-network

networks:
  internal-network:
    driver: bridge